### ISSUE TITLE
Socket in APSEthernet.h binds to first hardware interface

### ISSUE THREAD

**Issue by bcdonovan** [BBN-Q/libaps2#24]
The socket underneath the APSEthernet class [here](https://github.com/BBN-Q/libaps2/blob/8a33ff3a0f9497e1aaa6bcc11f157698afe55c0c/src/lib/APSEthernet.cpp#L3) binds to the first network interface on a system. 

For example on my test laptop eth0 is the wireless interface eth1 is the wired interface. As currently written the socket binds to eth0. flash attempts to send packets out the wireless interface rather than the wired interface (even though the wireless is turned off). 

I have also seen evidence of binding to the first network interface on a windows system.

I changed the endpoint to bind using ip address by using:

```
udp::endpoint(asio::ip::address::from_string("192.168.5.2"))
```

This forced flash and test_comms to used my wired interface.

I recommend that we add a method to set the ip address for binding and a command line switch to programs such as flash and test_comms to allow the user to select the network interface used to send the broadcast packets.

**Comment by caryan** [comment]
Another customer noted this and we provided a similar fix. It was noted in
the docs in 2da253f.

It's important to hear you've seen this too because I thought it was
limited to when two interfaces were active.

I'd prefer the user didn't have to worry about specifying interfaces and
that the driver just iterate over all of them. If I recall correctly it was
a pain to do that in a platform independent way.

The customer also pointed out our broadcast approach was old fashioned and
pointed to this SO question
http://stackoverflow.com/questions/683624/udp-broadcast-on-all-interfaces

**Comment by blakejohnson** [comment]
Rather than iterate over the interfaces, how about we iterate over the local IP addresses? This SO post describes how to get your local IPs from asio:

http://stackoverflow.com/questions/6327210/enumerating-ipv4-and-ipv6-address-of-my-cards-using-boost-asio

Then instead of sending a global broadcast to 255.255.255.255 just send broadcasts to the relevant subnets?

**Comment by caryan** [comment]
I like it.  I can try and tackle this.

**Comment by caryan** [comment]
Unfortunately, that SO post only works on Windows.  The comment on this [SO question](http://stackoverflow.com/questions/2674314/get-local-ip-address-using-boost-asio) suggests it is impossible from asio in a portable manner.
