### ISSUE TITLE
Occasionally unresponsive device (3.1)

### ISSUE THREAD

**Issue by dieris** [BBN-Q/libaps2#51]
Occasionally (~1/20 runs with 8 units, firmware 3.1) getting the following error:

`APS2 library call failed with message: Device failed to respond at requested IP address`

Communication is restored after `APS2.enumerate()`

**Comment by caryan** [comment]
Firmware 3.0 or 3.1?

**Comment by caryan** [comment]
Seems to be a firmware issue.  The routing table information is chucked out every 5 minutes.

**Comment by dieris** [comment]
new recurring message

`APS2 library call failed with message: Timed out while waiting to receive data.`

**Comment by caryan** [comment]
The original issue (`APS2 library call failed with message: Device failed to respond at requested IP address`) will be fixed in the 3.2 release.  The `APS2 library call failed with message: Timed out while waiting to receive data.` is a little more concerning.  I didn't see any comms error LEDs this morning so it means the TCP stream is flaking out.

**Comment by caryan** [comment]
With a combination of:
1. firmware 3.2
2. commit 67b9389 to be less aggressive about assumed network speeds
3. no anti-virus firewall interfering

I'm going to close this. @dieris if this crops up again please open a new issue.
